# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d76d3f943e75ea314623bb232e8a59b933a2dd050164dff50830a5e32a758d431f8bb082e04044bdd2bd929051cf0b6e6158804e60299cdcc11638af6714f091

test:
  secret_key_base: 2c4aa823ad9e1622b85927557aaf5cdf3561b3374def33649d9c117d99db6a410e342ba725c833d47872182aadb9c3e632e14271093ac8d5792e88b5367f8b28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
